"""Initial migration.

Revision ID: 3abd8e291805
Revises: 
Create Date: 2021-12-18 20:19:04.694027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abd8e291805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chengyu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('derivation', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('word', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chengyu')
    # ### end Alembic commands ###
