"""empty message

Revision ID: 4eb5d7304b1a
Revises: 9024e221a15e
Create Date: 2021-12-22 17:53:58.530001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb5d7304b1a'
down_revision = '9024e221a15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'text')
    op.add_column('user', sa.Column('vocab_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vocab_size')
    op.add_column('log', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
