"""empty message

Revision ID: 58edc3cf6dd1
Revises: 9d3fe6aad25e
Create Date: 2021-12-23 14:37:03.772247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58edc3cf6dd1'
down_revision = '9d3fe6aad25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('characters_read', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('chapters_read', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('books_read', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('shows_watched', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'shows_watched')
    op.drop_column('user', 'books_read')
    op.drop_column('user', 'chapters_read')
    op.drop_column('user', 'characters_read')
    # ### end Alembic commands ###
