"""empty message

Revision ID: 60f23aa8d49a
Revises: 663f7de3f5bc
Create Date: 2021-12-25 22:40:26.002195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f23aa8d49a'
down_revision = '663f7de3f5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('character_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'character_size')
    # ### end Alembic commands ###
