"""empty message

Revision ID: 9d3fe6aad25e
Revises: bfce3156a92e
Create Date: 2021-12-23 11:23:25.606845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d3fe6aad25e'
down_revision = 'bfce3156a92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('log', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('log', 'date')
    # ### end Alembic commands ###
