"""empty message

Revision ID: a12121db403c
Revises: 599efdb0bd7a
Create Date: 2021-12-19 10:28:33.475848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12121db403c'
down_revision = '599efdb0bd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'milestone', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.drop_column('milestone', 'user_id')
    # ### end Alembic commands ###
