"""empty message

Revision ID: bfce3156a92e
Revises: 4eb5d7304b1a
Create Date: 2021-12-22 17:58:40.012821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfce3156a92e'
down_revision = '4eb5d7304b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'vocab_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'vocab_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
