"""empty message

Revision ID: e81c6fc4c29e
Revises: 60f23aa8d49a
Create Date: 2021-12-25 22:40:35.038712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81c6fc4c29e'
down_revision = '60f23aa8d49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'character_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'character_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
